### ISSUE TITLE
RAM usage over 100% always

### ISSUE THREAD

**Issue by teacoat** [kporten/uebersicht-sys-monitor#3]
My RAM usage seems to be over 100%? As you can see in the other widget behind it I am not using all of my RAM.

![screen shot 2018-05-02 at 11 11 33 am](https://user-images.githubusercontent.com/3913019/39531627-978fe33c-4df9-11e8-9528-73eaea62fc2d.png)

**Comment by teacoat** [comment]
That command returns 

`105.3
98.3`

**Comment by kporten** [comment]
Your system seems to be almost fully occupied (memory usage of `98.3`). The first value `105.3` will be shared through the virtual cpu cores already. But I fixed the problem for a memory value over 100% - now it is limited. You can download the widget again. The memory usage value includes the swap usage value and this value will be added and the sum of it is over 100%.

**Comment by teacoat** [comment]
Well, its not using 100% of my RAM with nothing open lol.
